# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build"

on:
  push:
    branches:
      - master
      - multiversion
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
      - multiversion
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup test
      uses: darenm/Setup-VSTest@v1

    - name: Build solution
      run: msbuild src/NgrokExtensionsSolution/NgrokExtensionsSolution.sln /p:Configuration=Release /v:m -restore /p:OutDir=../../../built

    - name: Test
      run: vstest.console.exe built\*test.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: NgrokExtensions.vsix
        path: built/**/*.vsix